title: Databricks Certified Data Engineer Associate Questions
description: These are memory based topics for the assessment v2 I appeared on Nov 2022. If found it useful, leave a ⭐ in the repo.
theme: jekyll-theme-cayman
