title: Databricks Certified Data Engineer Associate Questions
description: These are memory based topics for the assessment v2 I appeared on Nov 2022. This is also useful for v3 based on the feedback from candidates who appeared on Jan 2024. If found it useful, leave a ⭐ in the repo.
theme: jekyll-theme-cayman
